### ISSUE TITLE
text must not be empty

### ISSUE THREAD

**Issue by KikyoC** [ImOnlyFire/yaml-file-translator#1]
Helo, I have this error: Translating key: cosmetics (Remaining: 518 keys)
Translating key: cosmetics.main-menu (Remaining: 517 keys)
Translating key: cosmetics.main-menu.Sprays (Remaining: 516 keys)
Translating key: cosmetics.main-menu.Sprays.lore (Remaining: 515 keys)
Exception in thread "main" java.lang.IllegalArgumentException: text must not be empty
        at com.deepl.api.Translator.lambda$createHttpParams$0(Translator.java:762)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at com.deepl.api.Translator.createHttpParams(Translator.java:760)
        at com.deepl.api.Translator.translateText(Translator.java:173)
        at com.deepl.api.Translator.translateText(Translator.java:218)
        at me.onlyfire.translator.YamlTranslator.translateList(YamlTranslator.java:50)
        at me.onlyfire.translator.YamlTranslator.translateMap(YamlTranslator.java:38)
        at me.onlyfire.translator.YamlTranslator.translateMap(YamlTranslator.java:36)
        at me.onlyfire.translator.YamlTranslator.translateMap(YamlTranslator.java:36)
        at me.onlyfire.translator.YamlTranslator.translateMap(YamlTranslator.java:36)
        at me.onlyfire.translator.YamlTranslator.translateMap(YamlTranslator.java:20)
        at me.onlyfire.translator.TranslatorMain.main(TranslatorMain.java:62)
        
        

This is the command: java -jar yaml-file-translator-1.0-SNAPSHOT-all.jar -a {REDACTED} -i lang.yml -l FR

I don't really know what to do.
Can you help me please ?
Thank you in advance

**Comment by literallyfiro** [comment]
Should be fixed by https://github.com/literallyfiro/yaml-file-translator/commit/11d7f982c5af83cd526727828796ebf581b7a2d9
